// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: tWPDKUtQCm8vMjv2gx9Hwj
// Component: 0mHKAfacQV
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_blank_project.module.css"; // plasmic-import: tWPDKUtQCm8vMjv2gx9Hwj/projectcss
import sty from "./PlasmicCoolcubesexclusivitypage.module.css"; // plasmic-import: 0mHKAfacQV/css

export type PlasmicCoolcubesexclusivitypage__VariantMembers = {};

export type PlasmicCoolcubesexclusivitypage__VariantsArgs = {};
type VariantPropType = keyof PlasmicCoolcubesexclusivitypage__VariantsArgs;
export const PlasmicCoolcubesexclusivitypage__VariantProps =
  new Array<VariantPropType>();

export type PlasmicCoolcubesexclusivitypage__ArgsType = {};
type ArgPropType = keyof PlasmicCoolcubesexclusivitypage__ArgsType;
export const PlasmicCoolcubesexclusivitypage__ArgProps =
  new Array<ArgPropType>();

export type PlasmicCoolcubesexclusivitypage__OverridesType = {
  root?: p.Flex<"div">;
  coolcubes4235639876?: p.Flex<"input">;
};

export interface DefaultCoolcubesexclusivitypageProps {}

export const defaultCoolcubesexclusivitypage__Args: Partial<PlasmicCoolcubesexclusivitypage__ArgsType> =
  {};

function PlasmicCoolcubesexclusivitypage__RenderFunc(props: {
  variants: PlasmicCoolcubesexclusivitypage__VariantsArgs;
  args: PlasmicCoolcubesexclusivitypage__ArgsType;
  overrides: PlasmicCoolcubesexclusivitypage__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;
  const args = Object.assign(
    {},
    defaultCoolcubesexclusivitypage__Args,
    props.args
  );
  const $props = args;

  return (
    <React.Fragment>
      {}

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div
        data-plasmic-name={"root"}
        data-plasmic-override={overrides.root}
        data-plasmic-root={true}
        data-plasmic-for-node={forNode}
        className={classNames(
          projectcss.all,
          projectcss.root_reset,
          projectcss.plasmic_default_styles,
          projectcss.plasmic_mixins,
          sty.root
        )}
      >
        <input
          data-plasmic-name={"coolcubes4235639876"}
          data-plasmic-override={overrides.coolcubes4235639876}
          accessKey={"coolcubes-423563-9876" as const}
          className={classNames(
            projectcss.all,
            projectcss.input,
            sty.coolcubes4235639876
          )}
          defaultValue={"" as const}
          disabled={false}
          placeholder={"enter the exclusivity key" as const}
          size={1 as const}
          type={"password" as const}
          value={"" as const}
        />
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "coolcubes4235639876"],
  coolcubes4235639876: ["coolcubes4235639876"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  coolcubes4235639876: "input";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicCoolcubesexclusivitypage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicCoolcubesexclusivitypage__VariantsArgs;
    args?: PlasmicCoolcubesexclusivitypage__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicCoolcubesexclusivitypage__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicCoolcubesexclusivitypage__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicCoolcubesexclusivitypage__ArgProps,
      internalVariantPropNames: PlasmicCoolcubesexclusivitypage__VariantProps
    });

    return PlasmicCoolcubesexclusivitypage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCoolcubesexclusivitypage";
  } else {
    func.displayName = `PlasmicCoolcubesexclusivitypage.${nodeName}`;
  }
  return func;
}

export const PlasmicCoolcubesexclusivitypage = Object.assign(
  // Top-level PlasmicCoolcubesexclusivitypage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    coolcubes4235639876: makeNodeComponent("coolcubes4235639876"),

    // Metadata about props expected for PlasmicCoolcubesexclusivitypage
    internalVariantProps: PlasmicCoolcubesexclusivitypage__VariantProps,
    internalArgProps: PlasmicCoolcubesexclusivitypage__ArgProps
  }
);

export default PlasmicCoolcubesexclusivitypage;
/* prettier-ignore-end */
